"use client";
import { DashboardIcon as Glyph } from "@/components/dashboard-icon";
import { WorkspaceOverview } from "@/components/workspace-overview";
import { PublishingCalendar } from "@/components/publishing-calendar";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useRef, useState, type FormEvent } from "react";
import { SocialIcon } from "@/components/mocks";

const initialPosts = [
  { title:"A fresh perspective", channel:"ig", image:"/apogix-workflow-coast.webp", status:"Scheduled", time:"Today · 10:30 AM" },
  { title:"Inside our creative process", channel:"li", image:"/apogix-about-studio.webp", status:"In review", time:"Tomorrow · 11:00 AM" },
  { title:"Make room for your ideas", channel:"fb", image:"/apogix-about-flow.webp", status:"Published", time:"Yesterday · 09:00 AM" },
] as const;
type Post = {title:string;channel:"ig"|"li"|"fb";image:string;status:string;time:string;scheduledAt?:string};
const customers=[{name:"Studio North",owner:"Maya Chen",plan:"Professional",status:"Active",accounts:8},{name:"Coast & Co.",owner:"Alex Morgan",plan:"Agency",status:"Active",accounts:21},{name:"Olive Creative",owner:"Sam Rivera",plan:"Starter",status:"Trial",accounts:3},{name:"Frame Studio",owner:"Jordan Lee",plan:"Professional",status:"Payment due",accounts:6}];


export function Dashboard({admin=false}:{admin?:boolean}){
 const [tab,setTab]=useState("Overview"),[menu,setMenu]=useState(false),[query,setQuery]=useState(""),[filter,setFilter]=useState("All"),[period,setPeriod]=useState("This week"),[posts,setPosts]=useState<Post[]>([...initialPosts]),[notice,setNotice]=useState(""),[selected,setSelected]=useState<string|null>(null);
 const [theme,setTheme]=useState("light");
 useEffect(()=>{try{setTheme(localStorage.getItem("apogix-dashboard-theme")||(matchMedia("(prefers-color-scheme: dark)").matches?"dark":"light"))}catch{}},[]);
 function toggleTheme(){const next=theme==="light"?"dark":"light";setTheme(next);try{localStorage.setItem("apogix-dashboard-theme",next)}catch{}}
 const [slotDate,setSlotDate]=useState("");
 const [composerKey,setComposerKey]=useState(0);
 function openComposer(date=""){setSlotDate(date);setComposerKey(k=>k+1);setSelected(null);dialog.current?.showModal()}
 const selectedPost=posts.find(p=>p.title===selected);
 const dialog=useRef<HTMLDialogElement>(null);
 const tabs=admin?["Overview","Customers","Publishing jobs","Analytics","Support"]:["Overview","Calendar","Posts","Media library","Approvals","Analytics","Connections"];
 const shown=posts.filter(p=>(filter==="All"||p.status===filter)&&p.title.toLowerCase().includes(query.toLowerCase()));
 function change(next:string){setTab(next);setMenu(false);setQuery("");setFilter("All");}
 function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);const title=String(data.get("title")).trim();if(!title)return;setPosts(old=>[{title,channel:data.get("channel") as Post["channel"],image:"/apogix-dashboard-banner.webp",status:data.get("scheduledAt")?"Scheduled":"Draft",time:data.get("scheduledAt")?new Date(String(data.get("scheduledAt"))).toLocaleString():"Not scheduled",scheduledAt:String(data.get("scheduledAt"))||undefined},...old]);dialog.current?.close();setNotice("Post saved in this demo session. Nothing has been published.");if(!slotDate)change("Posts");}
 const metrics=admin?[["Total workspaces","128","12 joined this month"],["Active subscriptions","96","75% of workspaces"],["Published destinations","8,420","Across all workspaces"],["Needs attention","7","3 failed jobs · 4 tickets"]]:[["Posts published",String(posts.filter(p=>p.status==="Published").length),"In your demo workspace"],["Scheduled",String(posts.filter(p=>p.status==="Scheduled").length),"Your next ideas, lined up"],["Awaiting review",String(posts.filter(p=>p.status==="In review").length),"Ready for a second look"],["Connected channels","3","Instagram · LinkedIn · Facebook"]];
 return <div data-theme={theme} className={`db-shell ${admin?"db-admin":""}`}>
  {menu&&<button className="db-scrim" aria-label="Close navigation" onClick={()=>setMenu(false)}/>}
  <aside className={`db-sidebar ${menu?"is-open":""}`}><Link href="/" className="db-logo"><Image src="/apogix-logo.webp" alt="Apogix home" width={139} height={40} priority/></Link><div className="db-workspace"><span className="db-avatar">{admin?"A":"S"}</span><div><strong>{admin?"Platform admin":"Studio workspace"}</strong><small>{admin?"Administration preview":"Demo workspace"}</small></div></div><span className="db-nav-label">{admin?"MANAGE PLATFORM":"YOUR WORKSPACE"}</span><nav aria-label="Dashboard navigation">{tabs.map(item=><button key={item} className={tab===item?"active":""} onClick={()=>change(item)} aria-current={tab===item?"page":undefined}><Glyph kind={item}/>{item}{item==="Approvals"&&<b>{posts.filter(p=>p.status==="In review").length}</b>}</button>)}</nav><div className="db-side-bottom"><div className="db-plan" hidden><span>{admin?"CONTROL WITH CLARITY":"MORE ROOM TO CREATE"}</span><strong>{admin?"A clearer overview.":"Find your next flow."}</strong><p>{admin?"Customers, publishing and support, together.":"Explore plans for your growing workspace."}</p><Link href={admin?"/contact":"/pricing"}>{admin?"Contact support":"Explore plans"} ↗</Link></div><Link href={admin?"/dashboard":"/admin"} className="db-switch">{admin?"User dashboard preview":"Admin dashboard preview"} ↗</Link><Link href="/" className="db-home">← Back to website</Link></div></aside>
  <div className="db-main"><header className="db-topbar"><div><button className="db-menu" aria-label="Open dashboard navigation" aria-expanded={menu} onClick={()=>setMenu(!menu)}><Glyph kind="Menu"/></button><span>{admin?"Administration":"Workspace"} <i>/</i> <strong>{tab}</strong></span></div><div className="db-top-actions"><button className="db-theme-toggle" aria-label="Toggle light or dark mode" aria-pressed={theme==="dark"} onClick={toggleTheme}><Glyph kind={theme==="dark"?"Sun":"Moon"}/><span>{theme==="dark"?"Light mode":"Dark mode"}</span></button><span className="db-demo">Demo preview</span><button aria-label="View notifications" onClick={()=>{setSelected("Notifications");dialog.current?.showModal()}} className="db-bell"><Glyph kind="Bell"/><i/></button><span className="db-avatar">{admin?"A":"S"}</span></div></header>
   <div className="db-content"><div className="db-page-heading"><div><span className="db-eyebrow">{admin?"YOUR PLATFORM, AT A GLANCE":"WORKSPACE OVERVIEW"}</span><h1>{tab==="Overview"?(admin?"A clear view. A better day.":"Let’s make today a good one."):tab}</h1><p>{admin?"Keep an eye on customers, content and the work that needs you.":"Plan, publish, and keep your team in sync."}</p></div><button className="db-primary" onClick={()=>{if(admin){setSelected("Platform report");dialog.current?.showModal()}else openComposer()}}>{admin?"View report":<><Glyph kind="Plus"/>Create post</>}</button></div>
   <div className="db-disclaimer">Illustrative data · {admin?"No real customer or billing data. Admin authentication is not connected.":"Sample workspace. Try creating a post or planning your week. Changes last for this session."}</div>
   {notice&&<div role="status" className="db-notice">{notice}<button aria-label="Dismiss notice" onClick={()=>setNotice("")}>×</button></div>}
   {admin&&tab==="Overview"&&<>{admin&&<section className="db-banner"><Image src="/apogix-dashboard-banner.webp" alt="Sunlit creative terrace with a flowing cobalt ribbon" fill priority sizes="(max-width: 800px) 100vw, 80vw"/><div><span className="db-eyebrow">{admin?"THE BIGGER PICTURE":"YOUR NEXT CHAPTER"}</span><h2>{admin?"Make every workspace\nfeel supported.":"Less busywork.\nMore brilliant ideas."}</h2><p>{admin?"See what’s growing. Focus on what needs attention.":"Your channels, content and creativity. In one happy place."}</p><button onClick={()=>change(admin?"Customers":"Calendar")}>{admin?"Explore workspaces":"Plan your week"} <span>↗</span></button></div></section>}<section className="db-metrics" aria-label="Demo summary">{metrics.map(([label,value,copy],i)=><div key={label}><span>{label}<Glyph kind={i===1?"Calendar":"Analytics"}/></span><strong>{value}</strong><small>{copy}</small></div>)}</section></>}
   {((admin&&tab==="Overview")||tab==="Analytics")&&<div className="db-two-col"><section className="db-panel"><div className="db-panel-head"><div><h2>{admin?"Publishing activity":"Your publishing rhythm"}</h2><p>Illustrative destinations published</p></div><select aria-label="Reporting period" value={period} onChange={e=>setPeriod(e.target.value)}><option>This week</option><option>Last week</option></select></div><div className="db-chart" aria-label={`${period}: demo publishing chart`}>{(period==="This week"?[28,55,40,78,61,91,68]:[45,32,65,48,80,59,72]).map((value,i)=><div key={i}><span>{admin?value*10:value}</span><i style={{height:`${value}%`}}/><small>{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"][i]}</small></div>)}</div><div className="db-chart-caption"><span><i/>Published destinations</span><span>Demo data · not live performance</span></div></section><section className="db-panel db-channel-panel"><div className="db-panel-head"><div><h2>{admin?"Platform health":"Your channels"}</h2><p>{admin?"Illustrative service snapshot":"Three voices. One workspace."}</p></div></div>{(["ig","li","fb"] as const).map((kind,i)=><div className="db-channel" key={kind}><SocialIcon kind={kind}/><div><strong>{["Instagram","LinkedIn","Facebook"][i]}</strong><small>{admin?"Provider connection service":"Studio workspace"}</small></div><span className="db-status">Demo</span></div>)}<button className="db-text-button" onClick={()=>change(admin?"Publishing jobs":"Connections")}>{admin?"Review publishing jobs":"Manage connections"} ↗</button></section></div>}
   {!admin&&["Posts","Approvals"].includes(tab)&&<section className="db-panel"><div className="db-panel-head"><div><h2>{tab==="Approvals"?"Ready for your review":"Your content, coming to life"}</h2><p>Keep the creative momentum going.</p></div>{tab==="Overview"&&<button className="db-text-button" onClick={()=>change("Posts")}>View all posts ↗</button>}</div><div className="db-filters"><input aria-label="Search posts" placeholder="Search your posts…" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Post status" value={filter} onChange={e=>setFilter(e.target.value)}>{["All","Draft","Scheduled","In review","Published"].map(x=><option key={x}>{x}</option>)}</select></div><div className="db-post-grid">{shown.filter(p=>tab!=="Approvals"||p.status==="In review").map((post,i)=><article className="db-post" key={post.title+i}><div className="db-post-image"><Image src={post.image} alt={post.title} width={480} height={300}/><span className={`db-status ${post.status==="In review"?"amber":""}`}>{post.status}</span></div><div className="db-post-body"><span className="db-post-meta"><SocialIcon kind={post.channel}/>{post.time}</span><h3>{post.title}</h3><button onClick={()=>{setSelected(post.title);dialog.current?.showModal()}}>Review post ↗</button>{post.status==="In review"&&<button className="db-approve" onClick={()=>{setPosts(old=>old.map(p=>p===post?{...p,status:"Draft",time:"Approved · ready to schedule"}:p));setNotice("Demo review recorded. Post returned to drafts, ready for scheduling.")}}>Approve demo</button>}</div></article>)}</div>{!shown.filter(p=>tab!=="Approvals"||p.status==="In review").length&&<p className="db-empty">No posts match this view.</p>}</section>}
   {!admin&&tab==="Overview"&&<WorkspaceOverview posts={posts} onNavigate={change} onCreate={()=>openComposer()} onOpen={title=>{setSelected(title);dialog.current?.showModal()}}/>}
   {!admin&&tab==="Calendar"&&<PublishingCalendar posts={posts} onAdd={openComposer} onOpen={title=>{setSelected(title);dialog.current?.showModal()}}/>}
   {!admin&&tab==="Media library"&&<section className="db-panel"><div className="db-panel-head"><div><h2>A little inspiration, on hand.</h2><p>Demo brand assets · select an image to inspect it</p></div></div><div className="db-media">{[...initialPosts,{title:"Creative terrace",image:"/apogix-dashboard-banner.webp"},{title:"Conversation",image:"/apogix-about-conversation.webp"},{title:"A new idea",image:"/apogix-about-idea.webp"}].map(item=><button key={item.title} onClick={()=>{setSelected(item.title);dialog.current?.showModal()}}><Image src={item.image} alt={item.title} width={400} height={300}/><span>{item.title}</span></button>)}</div></section>}
   {!admin&&tab==="Connections"&&<section className="db-panel"><div className="db-panel-head"><div><h2>Bring your channels together.</h2><p>Connection previews only. No provider access has been requested.</p></div></div>{(["ig","li","fb"] as const).map((kind,i)=><div className="db-channel" key={kind}><SocialIcon kind={kind}/><div><strong>{["Instagram","LinkedIn","Facebook"][i]}</strong><small>Official authorization required</small></div><button className="db-secondary" onClick={()=>setNotice("Social authorization is not configured yet. No account was connected.")}>Connect</button></div>)}</section>}
   {admin&&["Overview","Customers"].includes(tab)&&<section className="db-panel"><div className="db-panel-head"><div><h2>Workspaces worth watching</h2><p>Sample customers · all figures are illustrative</p></div><input aria-label="Search customers" placeholder="Find a workspace…" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="db-table-scroll"><table className="db-table"><thead><tr><th>Workspace</th><th>Plan</th><th>Accounts</th><th>Status</th><th>Details</th></tr></thead><tbody>{customers.filter(c=>(c.name+" "+c.owner).toLowerCase().includes(query.toLowerCase())).map((c,i)=><tr key={c.name}><td><div className="db-customer"><span className={`db-avatar tone-${i}`}>{c.name[0]}</span><div><strong>{c.name}</strong><small>{c.owner}</small></div></div></td><td>{c.plan}</td><td>{c.accounts}</td><td><span className={`db-status ${c.status!=="Active"?"amber":""}`}>{c.status}</span></td><td><button aria-label={`View ${c.name}`} onClick={()=>{setSelected(c.name);dialog.current?.showModal()}}>View ↗</button></td></tr>)}</tbody></table></div></section>}
   {admin&&tab==="Publishing jobs"&&<section className="db-panel"><div className="db-panel-head"><div><h2>Delivery needs a clear view.</h2><p>Sample queue · retry controls do not contact social platforms</p></div></div>{["Instagram · Studio North","LinkedIn · Coast & Co.","Facebook · Frame Studio"].map((job,i)=><div className="db-channel" key={job}><Glyph kind="Calendar"/><div><strong>{job}</strong><small>{i===0?"Access expired · reconnect required":i===1?"Waiting for scheduled time":"Temporary provider error"}</small></div><button className="db-secondary" onClick={()=>setNotice("Demo action only. No job was retried or modified on a server.")}>{i===0?"Inspect":"Review"}</button></div>)}</section>}
   {admin&&tab==="Support"&&<section className="db-panel"><div className="db-panel-head"><div><h2>A helping hand, when it matters.</h2><p>Sample support inbox</p></div></div>{["Unable to reconnect Instagram","Question about monthly usage","Invite a new team member"].map((subject,i)=><div className="db-channel" key={subject}><span className="db-avatar">{i+1}</span><div><strong>{subject}</strong><small>Demo ticket · awaiting review</small></div><button className="db-secondary" onClick={()=>{setSelected(subject);dialog.current?.showModal()}}>Open</button></div>)}</section>}
   <footer className="db-footer"><span>Apogix · A more thoughtful way to publish.</span><Link href="/contact">Help & support ↗</Link></footer>
   </div></div>
  <dialog ref={dialog} className="db-dialog"><button className="db-dialog-close" aria-label="Close dialog" onClick={()=>dialog.current?.close()}><Glyph kind="Close"/></button>{selected?<><span className="db-eyebrow">DEMO PREVIEW</span><h2>{selected}</h2>{selectedPost&&<div className="db-detail"><Image src={selectedPost.image} alt={selectedPost.title} width={600} height={350}/><div><SocialIcon kind={selectedPost.channel}/><strong>{({ig:"Instagram",li:"LinkedIn",fb:"Facebook"})[selectedPost.channel]}</strong><span className="db-status">{selectedPost.status}</span></div><p>{selectedPost.scheduledAt?new Date(selectedPost.scheduledAt).toLocaleString():selectedPost.time}</p></div>}<p>{selectedPost?"Preview your content here. This sample workspace does not publish to social accounts.":selected==="Notifications"?"You have one sample post waiting for review. There are no live notifications.":selected==="Platform report"?"128 sample workspaces, 96 active subscriptions and 8,420 published destinations. These are illustrative figures, not a live report.":"This is a sample record. MySQL persistence, authentication and live actions will be connected in the backend phase."}</p><button className="db-primary" onClick={()=>dialog.current?.close()}>Got it</button></>:<><span className="db-eyebrow">MAKE SOMETHING WORTH SHARING</span><h2>Create a post</h2><p>Choose a channel and an optional date. Leave the date empty to save a draft.</p><form key={composerKey} onSubmit={create}><label>Post title<input name="title" required maxLength={120} placeholder="Give your idea a name"/></label><label>Channel<select name="channel"><option value="ig">Instagram</option><option value="li">LinkedIn</option><option value="fb">Facebook</option></select></label><label>Schedule date & time <small>(optional)</small><input type="datetime-local" name="scheduledAt" defaultValue={slotDate}/></label><button className="db-primary" type="submit">Save post</button></form></>}</dialog>
 </div>;
}
