"use client";
import Image from "next/image";
import { DashboardIcon } from "./dashboard-icon";
import { SocialIcon } from "./mocks";
import type { CalendarPost } from "./publishing-calendar";
export function WorkspaceOverview({posts,onNavigate,onCreate,onOpen}:{posts:CalendarPost[];onNavigate:(tab:string)=>void;onCreate:()=>void;onOpen:(title:string)=>void}){
 const scheduled=posts.filter(p=>p.status==='Scheduled');
 const review=posts.filter(p=>p.status==='In review');
 const stats=[{label:'Scheduled posts',value:scheduled.length,copy:'Your next moments',icon:'Calendar',tab:'Calendar',tone:'purple'},{label:'Published posts',value:posts.filter(p=>p.status==='Published').length,copy:'Ideas out in the world',icon:'Posts',tab:'Posts',tone:'mint'},{label:'Awaiting approval',value:review.length,copy:'A little feedback to go',icon:'Approvals',tab:'Approvals',tone:'peach'},{label:'Draft ideas',value:posts.filter(p=>p.status==='Draft').length,copy:'Make something of them',icon:'Media library',tab:'Posts',tone:'pink'}];
 return <div className="wo-overview">
 <div className="wo-welcome-grid"><section className="wo-welcome"><div className="wo-welcome-copy"><span className="wo-kicker">A LITTLE FOCUS. A LOT OF POSSIBILITY.</span><h2>Big ideas.<br/>Meet your happy place.</h2><p>A fresh post, a thoughtful plan, a story worth sharing.<br/>What will you create today?</p><button onClick={onCreate}><DashboardIcon kind="Plus"/> Create something new</button></div><Image src="/apogix-dashboard-banner.webp" alt="Creative terrace with a flowing blue ribbon" fill priority sizes="(max-width:900px) 100vw, 65vw"/></section><section className="wo-focus"><span className="wo-kicker">YOUR NEXT STEP</span><div className="wo-focus-icon"><DashboardIcon kind={review.length?'Approvals':'Calendar'}/></div><h2>{review.length?`${review.length} post needs\nyour eye.`:'Make room for\nyour next idea.'}</h2><p>{review.length?'A quick review today. One less thing on your list tomorrow.':'Choose a date and give your next story a place to begin.'}</p><button onClick={()=>onNavigate(review.length?'Approvals':'Calendar')}>{review.length?'Review content':'Open calendar'}<DashboardIcon kind="Right"/></button></section></div>
 <section className="wo-stats" aria-label="Workspace summary">{stats.map(stat=><button key={stat.label} className={`wo-stat wo-${stat.tone}`} onClick={()=>onNavigate(stat.tab)}><div><span>{stat.label}</span><DashboardIcon kind={stat.icon}/></div><strong>{stat.value.toString().padStart(2,'0')}</strong><footer>{stat.copy}<DashboardIcon kind="Right"/></footer></button>)}</section>
 <div className="wo-content-grid"><section className="db-panel wo-posts"><div className="db-panel-head"><div><span className="wo-kicker">KEEP THE MOMENTUM</span><h2>Coming up next</h2></div><button className="db-text-button" onClick={()=>onNavigate('Calendar')}>Open calendar</button></div>{scheduled.length?<div className="wo-upcoming">{scheduled.map((post,i)=><button className="wo-upcoming-post" key={post.title+i} onClick={()=>onOpen(post.title)}><div className="wo-post-art"><Image src={post.image} alt="" width={500} height={300}/><span className="wo-post-badge"><SocialIcon kind={post.channel}/>{({ig:'Instagram',li:'LinkedIn',fb:'Facebook'})[post.channel]}</span></div><div className="wo-post-description"><span className="wo-scheduled">Scheduled</span><h3>{post.title}</h3><p>{post.scheduledAt?new Date(post.scheduledAt).toLocaleString([], {month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):post.time}</p></div></button>)}<button className="wo-plan-post" onClick={()=>onNavigate('Calendar')}><span><DashboardIcon kind="Plus"/></span><strong>Your next great post</strong><p>Pick a date. Make it happen.</p><b>Plan a post <DashboardIcon kind="Right"/></b></button></div>:<button className="wo-plan-post" onClick={()=>onNavigate('Calendar')}><span><DashboardIcon kind="Plus"/></span><strong>Your calendar is ready for a new idea.</strong><p>Choose a date to plan your first post.</p></button>}</section>
 <section className="db-panel wo-shortcuts"><div className="db-panel-head"><div><span className="wo-kicker">STRAIGHT TO IT</span><h2>Make your next move</h2></div></div>{[{title:'Write a post',copy:'Turn an idea into a draft',icon:'Posts',action:onCreate},{title:'Plan your week',copy:'Choose your perfect moment',icon:'Calendar',action:()=>onNavigate('Calendar')},{title:'Find your visuals',copy:'Your creative library, together',icon:'Media library',action:()=>onNavigate('Media library')},{title:'Connect a channel',copy:'Bring your accounts together',icon:'Connections',action:()=>onNavigate('Connections')}].map((item,i)=><button className={`wo-shortcut wo-shortcut-${i}`} key={item.title} onClick={item.action}><span><DashboardIcon kind={item.icon}/></span><div><strong>{item.title}</strong><small>{item.copy}</small></div><DashboardIcon kind="Right"/></button>)}</section></div>
 <section className="db-panel wo-recent"><div className="db-panel-head"><div><span className="wo-kicker">ALL YOUR IDEAS, TOGETHER</span><h2>Your content at a glance</h2></div><button className="db-text-button" onClick={()=>onNavigate('Posts')}>View all posts</button></div>{posts.slice(0,4).map((post,i)=><button className="db-recent-row" onClick={()=>onOpen(post.title)} key={post.title+i}><Image src={post.image} alt="" width={60} height={48}/><div><strong>{post.title}</strong><small>{post.time}</small></div><SocialIcon kind={post.channel}/><span className="db-status">{post.status}</span><DashboardIcon kind="Right"/></button>)}</section>
 </div>
}
