import { FeatureCalendar } from "@/components/feature-calendar";
import type { Metadata } from "next";
import Image from "next/image";
import { ArrowRight, Check } from "@/components/icons";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";
import { FloatingActions } from "@/components/floating-actions";
import { FeaturesMotion } from "@/components/features-motion";
import { FaqAccordion } from "@/components/faq-accordion";
import { brand } from "../../../../packages/config/brand";

export const metadata: Metadata = { title: `Features | ${brand.name}`, description: `Explore the ${brand.name} workflow: master composer, social scheduling, content calendar, team approvals and publishing analytics.` };

const features = [
  { id: "composer", label: "Master composer", title: "One starting point.\nEvery version, considered.", copy: "Start with your core idea, then give each channel the attention it deserves. Keep media, captions and destination choices connected instead of rebuilding the same post from scratch.", image: "/apogix-master-composer.webp", alt: "Apogix composer concept showing a master caption, channel versions and post preview", points: [["Master content", "Build a shared caption and media sequence as the starting point for your post."], ["Channel-specific versions", "Adapt copy and media for each destination while keeping the original idea close."], ["Preview before you publish", "Review the intended format and account, and catch missing content before scheduling."]], outcome: "One idea stays connected to every version.", link: "Explore compatible channels", href: "/integrations" },
  { id: "scheduling", label: "Smart scheduling", title: "Pick the moment.\nKeep the plan in motion.", copy: "Move from a finished draft to a clear publishing plan. Choose a time intentionally and keep track of what is waiting, what has published and what needs another look.", image: "/apogix-scheduling-visual-v2.webp", alt: "Scheduling concept with post preparation and planned publishing times", points: [["Timezone-aware planning", "Choose a publishing date and time in the context of your workspace timezone."], ["Destination-level progress", "Follow each selected account separately when a post is going to multiple channels."], ["Understand interruptions", "The planned delivery flow distinguishes temporary failures from problems that need an edit or reconnection."]], outcome: "A clear next step for every scheduled destination.", link: "Discuss your publishing workflow", href: "/contact" },
  { id: "calendar", label: "Content calendar", title: "See the week.\nShape the bigger picture.", copy: "Give your content a place in the bigger plan. A shared calendar brings timing and status into view so your team can spot gaps and coordinate what comes next.", image: "/apogix-calendar-photos.webp", alt: "Visual content planning concept with calendar dates and creative photography", points: [["Multiple perspectives", "The calendar is designed around month, week and list views for different planning needs."], ["Find the work that matters", "Planned filters help narrow the view by platform, team member and publishing status."], ["Thoughtful rescheduling", "Changes to eligible scheduled posts should confirm the intended time and timezone before updating the plan."]], outcome: "Less searching. A more connected content plan.", link: "Find a plan for your team", href: "/pricing" },
  { id: "approvals", label: "Team approvals", title: "Better feedback.\nA clearer final say.", copy: "Keep review connected to the content it belongs to. The approvals workflow is designed to give editors and reviewers a shared path from first draft to an agreed version.", image: "/apogix-approvals-visual.webp", alt: "Team approval workflow concept with content review and feedback", points: [["A deliberate handoff", "Editors submit a draft for review instead of relying on scattered chat messages."], ["Actionable decisions", "Reviewers can comment, approve or request changes in the planned approval flow."], ["Version-aware review", "Changes after approval follow workspace policy, with decisions recorded against the content version."]], outcome: "Feedback with context. Decisions with a history.", link: "Talk about team collaboration", href: "/contact" },
  { id: "analytics", label: "Analytics & visibility", title: "Understand the outcome.\nInform the next idea.", copy: "Start with a clear view of publishing activity. Understand what reached its destination and where attention is needed before drawing conclusions about performance.", image: "/apogix-analytics-visual.webp", alt: "Illustrative analytics dashboard showing social content reporting", points: [["Publishing visibility", "The core direction is a readable history of delivery status, errors and destination outcomes."], ["Channel context", "Interpret each post alongside its destination instead of treating every platform as identical."], ["Performance insights", "Deeper engagement reporting is part of the product roadmap. Available metrics depend on platform access and verified integrations."]], outcome: "Useful context for your next publishing decision.", link: "Ask about reporting needs", href: "/contact" },
];

const faqs = [
  { q: "How do these features work together?", a: "The intended workflow starts with a master post, adds channel-specific versions, moves through review where needed, and places approved content on the publishing calendar. Destination outcomes then help you understand what happened." },
  { q: "Are all features shown here available today?", a: "This page presents the Apogix product workflow and interface concepts. Availability varies by release, plan and platform permissions. Team approvals and deeper performance analytics are part of the staged product direction; contact us to confirm the capabilities available for your setup." },
  { q: "Does one post work exactly the same on every channel?", a: "No. Account eligibility, media formats and publishing permissions vary by platform. The composer is designed to keep a shared starting point while allowing each destination to have its own version." },
  { q: "Can I use Apogix for multiple clients?", a: "The product is designed around separate workspaces and authorized social accounts. Tell us about your client count, team roles and approval process so we can discuss a suitable setup." },
];

export default function FeaturesPage() {
  return <><SiteHeader/><main id="top" className="features-page"><FeaturesMotion/>
    <section className="features-hero"><div className="container"><div className="features-hero-copy"><span className="eyebrow">The Apogix toolkit</span><h1>From first thought<br/>to <span>thoughtfully published.</span></h1><p>Compose, adapt, plan and review. Explore the tools designed to bring your entire social publishing workflow together.</p><div className="features-hero-actions"><a href="#composer" className="btn btn--primary btn--lg">Explore the features<ArrowRight width={18} height={18}/></a><a href="/contact" className="features-text-link">Talk to our team<ArrowRight width={18} height={18}/></a></div></div><div className="features-hero-preview"><Image src="/apogix-master-composer.webp" alt="Apogix publishing workspace concept with composer and channel preview" width={1536} height={1024} priority sizes="(max-width: 760px) 95vw, 85vw"/><div className="features-preview-caption"><span>ONE IDEA. ONE CONNECTED WORKFLOW.</span><span>Product interface concept</span></div></div></div></section>
    <nav className="features-nav" aria-label="Feature sections"><div className="container">{features.map((feature,index)=><a key={feature.id} href={`#${feature.id}`}><span>0{index+1}</span>{feature.label}</a>)}</div></nav>
    <section className="features-intro"><div className="container"><span className="eyebrow">Less switching. More creating.</span><h2>Five parts.<br/>One considered workflow.</h2><p>Each tool solves a different part of the publishing process. Together, they keep the idea, the people and the plan connected.</p></div></section>
    {features.map((feature,index)=><section className={`section feature-detail feature-detail-${feature.id}`} id={feature.id} key={feature.id}><div className="container feature-detail-layout"><div className="feature-detail-copy"><span className="eyebrow">0{index+1} / {feature.label}</span><h2>{feature.title.split("\n").map((line,i)=><span key={line}>{i>0&&<br/>}{line}</span>)}</h2><p className="feature-description">{feature.copy}</p><ul>{feature.points.map(([title,copy])=><li key={title}><Check width={17} height={17}/><div><h3>{title}</h3><p>{copy}</p></div></li>)}</ul><a className="features-text-link" href={feature.href}>{feature.link}<ArrowRight width={18} height={18}/></a></div><div className="feature-detail-visual"><div className="feature-visual-index"><span>{feature.label}</span><span>0{index+1} / 05</span></div><div>{feature.id === "calendar" ? <FeatureCalendar/> : <Image src={feature.image} alt={feature.alt} width={1536} height={1024} sizes="(max-width: 900px) 90vw, 52vw"/>}</div><div className="feature-outcome"><span aria-hidden="true">↗</span><p>{feature.outcome}</p></div></div></div></section>)}
    <section className="section features-handoff"><div className="container"><span className="eyebrow">From draft to done</span><h2>A natural next step.<br/>At every step.</h2><div className="features-process">{[["Create", "Shape the master idea."],["Adapt", "Make each channel version fit."],["Review", "Bring feedback into focus."],["Schedule", "Give the content its moment."],["Learn", "Review the publishing outcome."]].map(([title,copy],index)=><div key={title}><span>0{index+1}</span><h3>{title}</h3><p>{copy}</p></div>)}</div></div></section>
    <section className="section features-faq"><div className="container features-faq-layout"><div><span className="eyebrow">A little more clarity</span><h2>Before you<br/>find your flow.</h2><p>Answers about the workflow, availability and channel differences.</p></div><FaqAccordion items={faqs}/></div></section>
    <section className="features-closing"><div className="container"><div><span className="eyebrow">Built around the way you work</span><h2>Make room for<br/>your next great post.</h2><p>Let’s talk about the channels, people and publishing rhythm that matter to you.</p><a href="/contact" className="btn btn--white btn--lg">Find your workflow<ArrowRight width={18} height={18}/></a></div><Image src="/apogix-about-idea.webp" alt="Creative idea bulb with floating paper and pencil" width={1280} height={1280} sizes="(max-width: 760px) 70vw, 32vw"/></div></section>
  </main><SiteFooter/><FloatingActions/></>;
}
